#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources=$XDG_CONFIG_HOME/x11/Xresources
usermodmap=$HOME/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
   done
   unset f
fi

sudo brightnessctl s 96000

# hide mouse cursor after 1 second of inactivity
unclutter --timeout 1 --fork

xrandr | grep '^DP-[0-9]-[0-9] connected' && $HOME/.screenlayout/office.sh

$HOME/bin/fehbg

# sudo dhcpcd
# wifi connect &

exec dwm
