"j"        = "next"
"<down>"   = "next"
"k"        = "prev"
"<up>"     = "prev"
"S-j"      = "move-next"
"S-<down>" = "move-next"
"S-k"      = "move-prev"
"S-<up>"   = "move-prev"
"q"        = "quit"
"S-q"      = "abort"
"h"        = "go-to-parent"
"<ret>"    = "enter-dir"
"l"        = "enter-dir"
"<spc>"    = "toggle-select"
"<tab>"    = "cycle"
"z"        = "hide-show"
"/"        = "filter"
