tui:
  selection:
    foreground: yellow
    bold: true
board:
    id: 358
    name: Architecture Board
    type: simple
epic:
    name: ""
    link: ""
installation: Cloud
issue:
    fields:
        custom:
            - name: Sprint
              key: customfield_10007
              schema:
                datatype: array
                items: json
            - name: Rank
              key: customfield_10400
              schema:
                datatype: any
            - name: Development
              key: customfield_12100
              schema:
                datatype: any
            - name: Teams
              key: customfield_13725
              schema:
                datatype: option
            - name: Flagged
              key: customfield_10002
              schema:
                datatype: array
                items: option
            - name: Story point estimate
              key: customfield_12842
              schema:
                datatype: number
            - name: Issue color
              key: customfield_12844
              schema:
                datatype: string
    types:
        - id: "10673"
          name: Story
          handle: Story
          subtask: false
        - id: "10674"
          name: Task
          handle: Task
          subtask: false
        - id: "10675"
          name: Bug
          handle: Bug
          subtask: false
        - id: "10676"
          name: Epic
          handle: Epic
          subtask: false
        - id: "10677"
          name: Subtask
          handle: Subtask
          subtask: true
login: david.grisham@pluto.tv
project:
    key: ARCH
    type: next-gen
server: https://plutotv.atlassian.net
